#!/bin/sh
# Exemples de commandes
curl -d '{"type":"connection"}' -H "Content-Type: application/json" -X POST http://localhost:3000/PSC/connexion
curl -d '{"type":"connection"}' -H "Content-Type: application/json" -X POST http://localhost:3000/FSC/connexion
curl -d '{"number":4}' -H "Content-Type: application/json" -X POST http://localhost:3000/FSC/set_firetruck_number
curl -d '{"number":6}' -H "Content-Type: application/json" -X POST http://localhost:3000/PSC/set_vehicle_number
curl -d '{"route":"Route 66"}' -H "Content-Type: application/json" -X POST http://localhost:3000/FSC/set_route_firetruck
curl -d '{"route":"Route 50"}' -H "Content-Type: application/json" -X POST http://localhost:3000/PSC/set_route_vehicle
curl -X GET http://localhost:3000/PSC/get_route_fire_truck
curl -X GET http://localhost:3000/FSC/get_route_police_vehicle
curl -d '{"response":"agree"}' -H "Content-Type: application/json" -X POST http://localhost:3000/FSC/response_route_fire_truck
curl -d '{"response":"agree"}' -H "Content-Type: application/json" -X POST http://localhost:3000/FSC/response_route_police_vehicle
sleep 2
curl -X POST http://localhost:3000/FSC/dispatch_fire_truck
curl -X POST http://localhost:3000/FSC/enough_fire_trucks_dispatched
curl -X POST http://localhost:3000/PSC/dispatch_police_vehicle
curl -X POST http://localhost:3000/PSC/enough_police_vehicles_dispatched
curl -X POST http://localhost:3000/FSC/enough_fire_trucks_arrived
curl -X POST http://localhost:3000/PSC/enough_police_vehicles_arrived

# Add police vehicle to the database
# curl -d '{"name":"Police Vehicle #1"}' -H "Content-Type: application/json" -X POST http://localhost:3000/System/add_police_vehicle

# Add fire truck to the database
# curl -d '{"name":"Fire truck #1"}' -H "Content-Type: application/json" -X POST http://localhost:3000/System/add_fire_truck